# Generated by Django 4.0.5 on 2022-06-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_comments_people_comments_person_id_auction_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_item',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='auction_item',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='auction_item',
            name='photo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='auction_item',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comments_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='bids',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='person_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
