# Generated by Django 4.0.5 on 2022-06-30 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auction_item_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_item',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='people',
            name='bids',
        ),
        migrations.RemoveField(
            model_name='people',
            name='comments',
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('bid_id', models.AutoField(primary_key=True, serialize=False)),
                ('bids', models.CharField(max_length=60, null=True)),
                ('person_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='auctions.people')),
            ],
        ),
    ]
