# Generated by Django 4.0.5 on 2022-06-30 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_auction_item_comments_remove_people_bids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='page_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.auction_item'),
        ),
    ]
