# Generated by Django 4.0.5 on 2022-06-30 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_comments_page_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_item',
            old_name='person_id',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='bids',
            old_name='person_id',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='page_id',
            new_name='page',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='person_id',
            new_name='person',
        ),
    ]
