# Generated by Django 4.0.5 on 2022-06-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_person_id_auction_item_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_item',
            name='desc',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
