# Generated by Django 4.0.5 on 2022-06-30 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_people_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.auction_item'),
        ),
    ]
