# Generated by Django 4.0.5 on 2022-07-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_bids_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_item',
            name='photo',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
