# Generated by Django 4.0.5 on 2022-07-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_auction_item_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bids',
            field=models.IntegerField(max_length=60, null=True),
        ),
    ]
