# Generated by Django 4.0.5 on 2022-07-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_bids_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bids',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='watchlist',
            field=models.JSONField(max_length=3000, null=True),
        ),
    ]
