# Generated by Django 4.0.5 on 2022-07-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_bids_bids_alter_people_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='watchlist',
            field=models.IntegerField(null=True),
        ),
    ]
