# Generated by Django 4.0.5 on 2022-07-01 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_people_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='watchlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.auction_item'),
        ),
    ]
