# Generated by Django 4.0.5 on 2022-07-01 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_people_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment', to='auctions.people'),
        ),
    ]
