# Generated by Django 4.0.5 on 2022-07-01 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_comments_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='watchlist',
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='auctions.people')),
                ('watchlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.auction_item')),
            ],
        ),
    ]
